"""Server-rendered shells for Giraffe's authenticated paper-trading UX.

No third-party design assets or frontend build pipeline are used.  The visual
language is independently implemented with semantic tokens inspired by the
public SEED design-system principles, not an official integration.
"""
from pathlib import Path

from .config import SIGNUP_ENABLED

AUTH_HTML = r'''<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Giraffe · 로그인</title>
<style>
:root{--primary:#3b82f6;--primary-low:#eaf2ff;--paper:#fffaf6;--sheet:#fff;--ink:#1f1d1b;--ink-low:#6d6863;--divider:#e9e1da;--danger:#c73524;--danger-low:#fff0ee;--success:#126b49;--warning:#a95b00;--radius-sm:12px;--radius:16px;--radius-lg:20px;--shadow:0 10px 30px rgba(68,43,24,.08)}
*{box-sizing:border-box}html{background:var(--paper);color:var(--ink);font:16px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{margin:0;min-width:0}.auth-layout{min-height:100dvh;display:grid;place-items:center;padding:24px}.auth-card{width:min(100%,440px);background:var(--sheet);border:1px solid var(--divider);border-radius:var(--radius-lg);padding:32px;box-shadow:var(--shadow)}.brand{display:flex;align-items:center;gap:10px;font-size:1.25rem;font-weight:800;letter-spacing:-.03em}.giraffe-dot{width:28px;height:28px;border-radius:50% 50% 45% 45%;background:radial-gradient(circle at 35% 30%,#fff 0 10%,transparent 11%),radial-gradient(circle at 67% 60%,#fff 0 8%,transparent 9%),var(--primary);border:3px solid #174ea6}.eyebrow{color:var(--primary);font-size:.875rem;font-weight:700;margin:28px 0 4px}h1{font-size:1.75rem;line-height:1.25;letter-spacing:-.04em;margin:0 0 8px}p{color:var(--ink-low)}.paper-note{background:var(--primary-low);border-radius:var(--radius-sm);padding:12px 14px;font-size:.875rem;margin:20px 0}.auth-mode{display:flex;gap:8px;margin:20px 0}.mode-button{flex:1;border:1px solid var(--divider);border-radius:12px;background:var(--sheet);color:var(--ink);font:inherit;font-weight:700;min-height:44px;cursor:pointer}.mode-button[aria-pressed="true"]{border-color:var(--primary);background:var(--primary-low);color:var(--primary)}label{display:block;font-size:.875rem;font-weight:700;margin-top:14px}input{display:block;width:100%;border:1px solid var(--divider);border-radius:12px;background:var(--sheet);color:var(--ink);font:inherit;min-height:48px;padding:0 12px;margin-top:6px}.password-wrap{position:relative}.password-wrap input{padding-right:72px}.show-password{position:absolute;right:4px;bottom:4px;width:auto;border:0;background:transparent;color:var(--primary);font:inherit;font-weight:700;min-height:40px;padding:0 10px;cursor:pointer}.alert{min-height:24px;margin:16px 0 0;color:var(--danger);font-size:.875rem}.submit{width:100%;border:0;border-radius:12px;background:var(--primary);color:var(--ink);font:inherit;font-weight:800;min-height:48px;margin-top:18px;cursor:pointer}.submit:disabled{opacity:.55;cursor:wait}button:focus-visible,input:focus-visible{outline:3px solid rgba(59,130,246,.38);outline-offset:2px}@media (prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}@media(max-width:390px){.auth-layout{padding:16px}.auth-card{padding:24px 20px}}
</style></head><body><main class="auth-layout"><section class="auth-card" aria-labelledby="auth-title"><div class="brand"><span class="giraffe-dot" aria-hidden="true"></span>Giraffe</div><p class="eyebrow">국내주식 계획을 차분하게</p><h1 id="auth-title">모의투자 계획을 시작하세요</h1><p>승인된 결정 카드의 진입·청산 규칙을 기록하고, 시세를 입력해 모의로 평가합니다.</p><aside class="paper-note"><strong>모의투자 전용</strong> · 실제 주문이나 증권사 연결은 제공하지 않습니다.</aside>__SIGNUP_UI__<div id="alert" class="alert" role="alert" aria-live="assertive"></div><form id="auth-form"><label for="email">이메일</label><input id="email" type="email" autocomplete="email" required placeholder="name@example.com"><label for="password">비밀번호</label><div class="password-wrap"><input id="password" type="password" autocomplete="current-password" required minlength="8" placeholder="비밀번호를 입력하세요"><button class="show-password" type="button" aria-controls="password" aria-pressed="false">보기</button></div><button id="submit" class="submit" type="submit">로그인</button></form></section></main><script>
const $=s=>document.querySelector(s),alertEl=$('#alert'),form=$('#auth-form'),password=$('#password'),submit=$('#submit');__SIGNUP_SCRIPT__$('.show-password').addEventListener('click',e=>{const visible=password.type==='text';password.type=visible?'password':'text';e.currentTarget.textContent=visible?'보기':'숨기기';e.currentTarget.setAttribute('aria-pressed',String(!visible))});form.addEventListener('submit',async e=>{e.preventDefault();alertEl.textContent='';if(!form.checkValidity()){form.reportValidity();return}submit.disabled=true;submit.textContent='처리 중…';try{const r=await fetch(__AUTH_ENDPOINT__,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value.trim(),password:password.value})});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'입력 내용을 확인하세요');location.assign('/app')}catch(err){alertEl.textContent=err.message;submit.disabled=false;submit.textContent=__SUBMIT_TEXT__}});
</script></body></html>'''

AUTH_HTML = AUTH_HTML.replace(
    "__SIGNUP_UI__",
    '<div class="auth-mode" role="group" aria-label="계정 선택"><button id="login-mode" class="mode-button" type="button" aria-pressed="true">로그인</button><button id="signup-mode" class="mode-button" type="button" aria-pressed="false">회원가입</button></div>' if SIGNUP_ENABLED else "",
).replace(
    "__SIGNUP_SCRIPT__",
    "let mode='login';const setMode=next=>{mode=next;alertEl.textContent='';password.autocomplete=mode==='signup'?'new-password':'current-password';submit.textContent=mode==='signup'?'회원가입':'로그인';$('#auth-title').textContent=mode==='signup'?'회원가입':'모의투자 계획을 시작하세요';$('#login-mode').setAttribute('aria-pressed',String(mode==='login'));$('#signup-mode').setAttribute('aria-pressed',String(mode==='signup'))};$('#login-mode').addEventListener('click',()=>setMode('login'));$('#signup-mode').addEventListener('click',()=>setMode('signup'));" if SIGNUP_ENABLED else "",
).replace(
    "__AUTH_ENDPOINT__", "mode==='signup'?'/api/signup':'/api/login'" if SIGNUP_ENABLED else "'/api/login'",
).replace("__SUBMIT_TEXT__", "mode==='signup'?'회원가입':'로그인'" if SIGNUP_ENABLED else "'로그인'")

APP_HTML = Path(__file__).with_name('decision_card_app.html').read_text(encoding='utf-8')
PROTOTYPE_HTML = Path(__file__).with_name('prototype.html').read_text(encoding='utf-8')
